from ubinascii import hexlify
from machine import unique_id


__SENSOR_ID = hexlify(unique_id()).decode("utf-8").upper()
SENSOR_HOSTNAME = "WCS_SENSOR_" + __SENSOR_ID
SENSOR_SLEEP_AFTER_MEASUREMENT_SEC = 10  # 30
SENSOR_SLEEP_AFTER_FAILURE_SEC = 20

WLAN_NETWORK = "TP-LINK_M5_40490B"
WLAN_PASSWORD = "11880384"

MQTT_BROKER_HOST = "DESKTOP-US2KU7H.LOCAL"
#MQTT_BROKER_HOST = "DESKTOP-OU9RC1N.LOCAL"
MQTT_BROKER_PORT = 1883
MQTT_BROKER_USER_NAME = ""
MQTT_BROKER_USER_PASSWORD = ""
MQTT_BROKER_KEEPALIVE = SENSOR_SLEEP_AFTER_MEASUREMENT_SEC  # * 3

MQTT_TOPIC_ROOT = b"wcs/sensors/" + __SENSOR_ID.encode() + b"/"
MQTT_TOPIC_STATUS = b"status"
MQTT_TOPIC_LIQUID_SENSOR = b"liquid"

MQTT_TOPIC_STATUS_UP = b"up"
MQTT_TOPIC_STATUS_DOWN = b"down"
